/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wolfe;

public class App {
    public String getGreeting() {
        return "Hello Nuvalence! \n" +
        "This application is solely contained and will be \n" +
        "run only via the test suite.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
}
